Staff s21 publish docs
ucsb-cs156-s21/proj-ucsb-cs-las pull request #171
Opened 2021-04-24 23:06 UTC by pconrad

In this PR, we set up a GitHub workflow to publish the storybook for the repo.

The storybook is published on GitHub pages in two separate repos:
* <ucsb-cs156-s21/proj-ucsb-cs-las-docs> for the production version of the documentation
* <ucsb-cs156-s21/proj-ucsb-cs-las-docs-qa> as a staging/qa site for draft versions contained in PRs

One of the workflows is set up to publish to the production site, i.e. <https://ucsb-cs156-s21.github.io/proj-ucsb-cs-las-docs>, only on a push to the main branch (i.e. when a PR is merged.)

The other workflow is set up to publish to the QA branch any time there is a PR.  Note the implications: if there are multiple PRs outstanding, the contents of the qa GitHub pages site will always reflect the most recent PR that was made.   Teams will have to coordinate in order to review changes to the Storybook, so this is not a perfect solution. But it at least guarantees that if there are any problems with the publishing, those will get flagged as CI/CD errors, and it encourages teams to review the storybook before merging a PR.

The other sites need to be set up as follows:

First, add a file under `docs/index.md` that looks like this for the production docs site:

```
---
---

Documentation for <https://github.com/ucsb-cs156-s21/proj-ucsb-cs-las>

[Storybook](storybook)

```

And like this for the qa docs site:

```
---
---

Documentation QA site for <https://github.com/ucsb-cs156-s21/proj-ucsb-cs-las>

* Documentation on this site is for work in progress.
* The production version of the documentation is here: <ucsb-cs156-s21.github.io/proj-ucsb-cs-las-docs>

[Storybook](storybook)
```

Then, you can go to `Settings` for each of these repos, then `Pages` (near bottom of left nav) to enable GitHub Pages on the `main` branch and the `/docs` subdirectory.

It is also necessary to set up a Personal Access Token with scope `repo` and add it to the repository secrets.

2021-04-26 01:04 UTC, andrewhlu submitted a review, later dismissed

2021-04-27 01:53 UTC, andrewhlu requested changes
I think this is why the builds are failing - it appears that the Storybook is being output to the `javascript/storybook-static` directory instead of `javascript/docs-build`, which is causing the Actions deploy script to deploy nothing.

See the output of [this Actions workflow](https://github.com/ucsb-cs156-s21/proj-ucsb-cs-las/runs/2434116627?check_suite_focus=true#step:3:8276).

2021-04-27 01:53 UTC, andrewhlu commented on .github/workflows/publish-docs-to-github-pages-qa.yml
> +          folder: javascript/docs-build # The folder that the build-storybook script generates files.
```suggestion
          folder: javascript/storybook-static # The folder that the build-storybook script generates files.
```

2021-04-27 01:53 UTC, andrewhlu commented on .github/workflows/publish-docs-to-github-pages.yml
> +          folder: javascript/docs-build # The folder that the build-storybook script generates files.
```suggestion
          folder: javascript/storybook-static # The folder that the build-storybook script generates files.
```

2021-04-28 00:39 UTC, andrewhlu approved these changes

2021-04-28 00:45 UTC, btk5h approved these changes

2021-04-28 00:45 UTC, merged