ZW - AN - 6pm - Refactor Course Table
ucsb-cs156-s21/proj-ucsb-cs-las pull request #214
Opened 2021-05-12 20:11 UTC by Zwang1680

Refactored the coursetable to include just the default arrows not our own premade ones. Also edited the test file to no longer check for the made arrows.

2021-05-17 19:56 UTC, m-cabello submitted a review, later dismissed
Looks Good! You guys follow the instructions accurately/\.

2021-05-17 20:06 UTC, WadeVaresio requested changes
LGTM, will be ready to merge once the commented lines are removed.

2021-05-17 20:06 UTC, WadeVaresio commented on javascript/src/test/components/Courses/CourseTable.test.js
> +    // expect(getByText(descendingOFF)).toBeInTheDocument();
Please remove these commented out lines, we typically do not want to include commented out code.

2021-05-17 20:18 UTC, m-cabello submitted a review, later dismissed
Look Great!

2021-05-18 01:41 UTC, JacquelineMai approved these changes
LGTM
We've agreed to let this merge with the codecov failures, since we've confirmed that the test coverage isn't actually decreasing.

2021-05-18 04:49 UTC, mpbonham approved these changes
Everything looks good!

2021-05-18 09:34 UTC, merged