rb 6pm-4 - add a Download CSV button that downloads a CSV containing all ULA Tutor assignments
ucsb-cs156-s21/proj-ucsb-cs-las pull request #255
Opened 2021-05-26 20:23 UTC by rbapat100

2021-05-26 20:46 UTC, dorinori submitted a review, later dismissed
LGTM

2021-05-27 03:19 UTC, WadeVaresio requested changes
Tested on QA deployment, works as intended. Please see review comment about placing button above the table.

2021-05-27 03:19 UTC, WadeVaresio commented on javascript/src/main/pages/TutorAssignment/TutorAssignments.js
> +      <Button><CSVLink style={{color: "white"}} headers={headers} data={tutorAssignmentList} filename = {"TutorAssignments.csv"}>Download CSV</CSVLink></Button>
As the tutor assignments page increases in size, the download button is harder to find. Would we be able to place the download button above the table?

2021-05-28 02:38 UTC, bzamora020 approved these changes
LGTM!

2021-05-28 02:49 UTC, WadeVaresio approved these changes
LGTM

2021-05-28 02:50 UTC, merged