6pm-2 create frontend pages to add and display room slots
ucsb-cs156-s21/proj-ucsb-cs-las pull request #275
Opened 2021-05-28 09:55 UTC by rowantran

In this PR we add two pages to the frontend, enabling users to display a table with current physical room slots and add new ones.
Closes #244. Closes #248.

2021-05-28 17:16 UTC, RaghubirChimni commented
Need to add push some things before we can merge this into main

2021-05-28 22:45 UTC, btk5h requested changes

2021-05-28 22:45 UTC, btk5h commented on javascript/src/main/components/RoomSlots/RoomSlotForm.js
> +            //     updateRoomSlot({...roomSlot, quarter: formatedQuarter});
Can we remove the commented code here?

2021-05-29 03:17 UTC, noahcorona44 submitted a review, later dismissed
LGTM

2021-05-29 05:53 UTC, arunryu approved these changes
LGTM

2021-05-29 18:16 UTC, btk5h submitted a review, later dismissed

2021-05-29 18:16 UTC, btk5h commented on javascript/src/main/components/RoomSlots/RoomSlotForm.js
> +            let formattedQuarter = "20" + roomSlot.quarter.substr(1, 2) + quarterNum;
This logic can probably be refactored a bit and moved with the rest of the quarter format utilities.

2021-05-29 18:16 UTC, btk5h commented on javascript/src/main/components/RoomSlots/RoomSlotForm.js
> +const RoomSlotForm = ({ createRoomSlot/*, updateRoomSlot, existingRoomSlot*/}) =>{
Can we remove the comment here?

2021-05-29 18:16 UTC, btk5h commented on javascript/src/main/components/RoomSlots/RoomSlotTable.js
> +    };*/
Can we remove the commented code here?

2021-05-29 18:16 UTC, btk5h commented on javascript/src/main/pages/RoomSlots/RoomSlots.js
> +  }, [mutateRoomSlots]);
What is the purpose of this piece of code? It's not obvious what you're trying to accomplish here as I don't think the useSWR mutation function was intended to be used like this.

2021-05-29 18:16 UTC, btk5h commented on javascript/src/main/pages/RoomSlots/RoomSlots.js
> +    roleInfo && roleInfo.role && roleInfo.role.toLowerCase() === "admin";
I believe this long series of checks can be simplified to something like:
```suggestion
  const isAdmin = roleInfo?.role?.toLowerCase() === "admin";
```

2021-05-29 18:16 UTC, btk5h commented on javascript/src/main/utils/RoomSlotFormHelpers.js
> +const formatTimeToLocalTime = (time) => {
I don't think this needs to be addressed in this PR but it should be noted that this logic should be replaced with a proper date parsing/formatting library in a future refactoring story.

2021-05-29 18:16 UTC, btk5h commented on javascript/src/main/utils/RoomSlotTableHelpers.js
> +const toAMPMFormat = (time) => {
Similar to formatTimeToLocalTime, this doesn't have to be refactored in this PR but we should consider a dedicated library for this in the long run.

2021-05-29 18:16 UTC, btk5h commented on javascript/src/test/pages/RoomSlots/RoomSlots.test.js
> +}) ); */
Can we remove the commented code here?

2021-05-29 18:16 UTC, btk5h commented on javascript/src/test/pages/RoomSlots/RoomSlots.test.js
> +  //   });
If these tests are outdated, can you remove them? If they're commented out due to some other issues, can you use `test.skip` instead?

2021-05-29 22:05 UTC, noahcorona44 submitted a review, later dismissed
LGTM

2021-05-30 23:29 UTC, mara-downing submitted a review, later dismissed
When running on heroku qa, I get a toast notification that says "Error saving room slot" when I try to submit a new room. I am using the parameters "Library, "F20", "11:00AM", "2:00PM", Tuesday.

2021-05-31 17:49 UTC, mara-downing approved these changes
LGTM

2021-05-31 17:57 UTC, noahcorona44 approved these changes
LGTM - Reapproving changes. Nice job guys!

2021-05-31 21:28 UTC, merged